MOVEMENT_SCALE = 2.0

CLICK_THRESHOLD = 0.03

SMOOTHING_HISTORY_SIZE = 5
SMOOTHING_FACTOR = 0.7

CLICK_COOLDOWN = 0.5

DEAD_ZONE_THRESHOLD = 0.01

CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480

MIN_DETECTION_CONFIDENCE = 0.7
MIN_TRACKING_CONFIDENCE = 0.5
MAX_NUM_HANDS = 1
